# grub2-rpm-sort
# Autogenerated from man page /usr/share/man/man8/grub2-rpm-sort.8.gz
complete -c grub2-rpm-sort -s '?' -l help -d 'give this help list'
complete -c grub2-rpm-sort -l usage -d 'give a short usage message'
complete -c grub2-rpm-sort -s V -l version -d 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>'

