# h52gif
# Autogenerated from man page /usr/share/man/man1/h52gif.1.gz
complete -c h52gif -s i -d 'Image option, specifying the name of an HDF5 image or dataset containing an i…'
complete -c h52gif -s p

