# h5c++
# Autogenerated from man page /usr/share/man/man1/h5c++.1.gz
complete -c h5c++ -o help -d 'Prints a help message'
complete -c h5c++ -o echo -d 'Show all the shell commands executed'
complete -c h5c++ -o prefix -d 'Use the directory DIR to find the HDF5 lib/ and include/ subdirectories'
complete -c h5c++ -o show -d 'Show the commands without executing them'

