# h5cc
# Autogenerated from man page /usr/share/man/man1/h5cc.1.gz
complete -c h5cc -o help -d 'Prints a help message'
complete -c h5cc -o echo -d 'Show all the shell commands executed'
complete -c h5cc -o prefix -d 'Use the directory DIR to find the HDF5 lib/ and include/ subdirectories'
complete -c h5cc -o show -d 'Show the commands without executing them'
complete -c h5cc -o shlib -d 'Compile using shared HDF5 libraries'
complete -c h5cc -o noshlib -d 'Compile using static HDF5 libraries [default]'

