# h5copy
# Autogenerated from man page /usr/share/man/man1/h5copy.1.gz
complete -c h5copy -s i -l input -d 'input file name'
complete -c h5copy -s o -l output -d 'output file name'
complete -c h5copy -s s -l source -d 'source object name'
complete -c h5copy -s d -l destination -d 'destination object name P OPTIONS'
complete -c h5copy -s h -l help -d 'Print a usage message and exit'
complete -c h5copy -s p -l parents -d 'No error if existing, make parent groups as needed'
complete -c h5copy -s v -l verbose -d 'Print information about OBJECTS and OPTIONS'
complete -c h5copy -s V -l version -d 'Print version number and exit'
complete -c h5copy -s f -l flag -d 'Flag type P Flag type is one of the following strings:'

