# h5diff
# Autogenerated from man page /usr/share/man/man1/h5diff.1.gz
complete -c h5diff -s h -d 'Print all differences'
complete -c h5diff -s r -d 'Print only the names of objects that differ; do not print the differences'
complete -c h5diff -s n -d 'Print difference up to count differences, then stop'
complete -c h5diff -s d -d 'Print only differences that are greater than the limit delta'
complete -c h5diff -s p -d 'Print only differences that are greater than a relative error'

