# h5import
# Autogenerated from man page /usr/share/man/man1/h5import.1.gz
complete -c h5import -s h -d 'prints the h5import usage summary'
complete -c h5import -s d -d 'Input data dimensions'
complete -c h5import -s p -d 'pathname  is a string consisting of one or more strings separated by slashes …'
complete -c h5import -s t -d 'input_class  specifies the class of the input data and determines the class o…'
complete -c h5import -s s -d 'input_size  specifies the size in bits of the input data and determines the s…'
complete -c h5import -s c -d 'config_file  specifies a configuration file'

