# h5mkgrp
# Autogenerated from man page /usr/share/man/man1/h5mkgrp.1.gz
complete -c h5mkgrp -s h -l help -d 'Print a usage message and exit'
complete -c h5mkgrp -s l -l latest -d 'Use latest version of file format to create groups'
complete -c h5mkgrp -s p -l parents -d 'No error if existing, make parent groups as needed'
complete -c h5mkgrp -s v -l verbose -d 'Print information about OBJECTS and OPTIONS'
complete -c h5mkgrp -s V -l version -d 'Print version number and exit SEE ALSO The full documentation for h5mkgrp: is…'

