# h5perf_serial
# Autogenerated from man page /usr/share/man/man1/h5perf_serial.1.gz
complete -c h5perf_serial -s h -d 'Print an usage message and exit'
complete -c h5perf_serial -s A -d 'Which APIs to test [default: all of them]'
complete -c h5perf_serial -s c -d 'Selects chunked storage and defines chunks dimensions and sizes [default: Off]'
complete -c h5perf_serial -s e -d 'Dimensions and sizes of dataset [default: 100,200]'
complete -c h5perf_serial -s i -d 'Number of iterations to perform [default: 1]'
complete -c h5perf_serial -s r -d 'Dimension access order (see below for description) [default: 1,2]'
complete -c h5perf_serial -s t -d 'Selects extendable dimensions for HDF5 dataset [default: Off]'
complete -c h5perf_serial -s v -d 'Selects file driver for HDF5 access [default: sec2]'
complete -c h5perf_serial -s w -d 'Perform write tests, not the read tests [default: Off]'
complete -c h5perf_serial -s x -d 'Dimensions and sizes of the transfer buffer [default: 10,20]'

