# h5repack
# Autogenerated from man page /usr/share/man/man1/h5repack.1.gz
complete -c h5repack -s h -d 'Print a help message'
complete -c h5repack -s f -d 'Filter type'
complete -c h5repack -s l -d 'Layout type'
complete -c h5repack -s v -d 'Verbose mode'
complete -c h5repack -s e -d 'File with the  -f and  -l  options (only filter and layout flags)'
complete -c h5repack -s d -d 'Print only differences that are greater than the limit R delta '
complete -c h5repack -s m -d 'Do not apply the filter to objects which size in bytes is smaller  than number'

