# h5redeploy
# Autogenerated from man page /usr/share/man/man1/h5redeploy.1.gz
complete -c h5redeploy -o help -d 'Prints a help message'
complete -c h5redeploy -o echo -d 'Shows all the shell commands executed'
complete -c h5redeploy -o force -d 'Performs the requested action without offerring any prompt requesting confirm…'
complete -c h5redeploy -o prefix -d 'Specifies a new directory in which to find the HDF5 subdirectories lib/ and i…'
complete -c h5redeploy -o tool -d 'Specifies the tool to update'
complete -c h5redeploy -o show -d 'Shows all of the shell commands to be executed without actually executing them'

