# h5repart
# Autogenerated from man page /usr/share/man/man1/h5repart.1.gz
complete -c h5repart -s v -d 'Produce verbose output'
complete -c h5repart -s V -d 'Print a version number and exit'
complete -c h5repart -o bN -d 'The I/O block size, defaults to 1kB'
complete -c h5repart -o mN -d 'The destination member size or 1GB'

