# h5stat
# Autogenerated from man page /usr/share/man/man1/h5stat.1.gz
complete -c h5stat -s h -l help -d 'Print a usage message and exit'
complete -c h5stat -s V -l version -d 'Print version number and exit'
complete -c h5stat -s f -l file -d 'Print file information'
complete -c h5stat -s F -l filemetadata -d 'Print file space information for file\'s metadata'
complete -c h5stat -s g -l group -d 'Print group information'
complete -c h5stat -s G -l groupmetadata -d 'Print file space information for groups\' metadata'
complete -c h5stat -s d -l dset -d 'Print dataset information'
complete -c h5stat -s D -l dsetmetadata -d 'Print file space information for datasets\' metadata'
complete -c h5stat -s T -l dtypemetadata -d 'Print datasets\' datatype metadata'
complete -c h5stat -s A -l attribute -d 'Print attribute information SEE ALSO The full documentation for h5stat: is ma…'

