# osinfo-db-import
# Autogenerated from man page /usr/share/man/man1/osinfo-db-import.1.gz
complete -c osinfo-db-import -l user -d 'Override the default behaviour to force installation into the user database l…'
complete -c osinfo-db-import -l local -d 'Override the default behaviour to force installation into the local database …'
complete -c osinfo-db-import -l system -d 'Override the default behaviour to force installation into the system database…'
complete -c osinfo-db-import -l dir -d 'Override the default behaviour to force installation into the custom director…'
complete -c osinfo-db-import -l root -d 'Prefix the installation location with the root directory given by \\f(CW\\*(C`P…'
complete -c osinfo-db-import -l latest -d 'Downloads the latest osinfo-db release from libosinfo\'s official releases web…'

