# osinfo-db-path
# Autogenerated from man page /usr/share/man/man1/osinfo-db-path.1.gz
complete -c osinfo-db-path -l user -d 'Override the default behaviour to force reporting of the user database locati…'
complete -c osinfo-db-path -l local -d 'Override the default behaviour to force reporting of the local database locat…'
complete -c osinfo-db-path -l system -d 'Override the default behaviour to force reporting of the system database loca…'
complete -c osinfo-db-path -l dir -d 'Override the default behaviour to force reporting of the custom directory \\s-…'

