# osinfo-db-validate
# Autogenerated from man page /usr/share/man/man1/osinfo-db-validate.1.gz
complete -c osinfo-db-validate -l user -d 'Override the default behaviour to force validating files from the user databa…'
complete -c osinfo-db-validate -l local -d 'Override the default behaviour to force validating files from the local datab…'
complete -c osinfo-db-validate -l system -d 'Override the default behaviour to force validating files from the system data…'
complete -c osinfo-db-validate -l dir -d 'Override the default behaviour to force validating files from the custom dire…'
complete -c osinfo-db-validate -l root -d 'Prefix the database location with the root directory given by \\f(CW\\*(C`PATH\\…'

