# osinfo-db-export
# Autogenerated from man page /usr/share/man/man1/osinfo-db-export.1.gz
complete -c osinfo-db-export -l user -d 'Override the default behaviour to force archiving files from the user databas…'
complete -c osinfo-db-export -l local -d 'Override the default behaviour to force archiving files from the local databa…'
complete -c osinfo-db-export -l system -d 'Override the default behaviour to force archiving files from the system datab…'
complete -c osinfo-db-export -l dir -d 'Override the default behaviour to force archiving files from the custom direc…'
complete -c osinfo-db-export -l root -d 'Prefix the database location with the root directory given by \\f(CW\\*(C`PATH\\…'
complete -c osinfo-db-export -l version -d 'Set the version string for the files in the archive to \\s-1VERSION\\s0'
complete -c osinfo-db-export -l license -d 'Add \\f(CW\\*(C`LICENSE-FILE\\*(C\' to the generated archive as an entry named \\*…'

